"""
OpenVPN server with its own certificate authority (easy-rsa).
"""

import csv
import io
import ipaddress
import os
import time

from services.config import (
    load_defaults,
    load_running,
    load_system,
    save_system
)

from services import transaction

from services.network import run_command, privileged

from services.vpn_common import (
    which,
    valid_name,
    write_root_file,
    read_root_file,
    unit_active,
    start_unit,
    stop_unit,
    get_wan_interface,
    get_lan_networks,
    firewall_rules_for,
    sync_firewall
)

from services.network import unit_stays_active

# -------------------------------------------------------------------
# Configuration
# -------------------------------------------------------------------

# openvpn.json: server defaults in /etc/chaos-router-os,
# settings, keys and clients in /var/lib/chaos-router-os.
OPENVPN_SETTINGS = "openvpn"

SERVER_NAME = "chaos"
SERVER_DIR = "/etc/openvpn/server"
SERVER_CONF = f"{SERVER_DIR}/{SERVER_NAME}.conf"
SERVER_UNIT = f"openvpn-server@{SERVER_NAME}"
SERVER_DEVICE = "ovpns0"

# Written by Debian's openvpn-server@.service (--status-version 2).
STATUS_FILE = f"/run/openvpn-server/status-{SERVER_NAME}.log"

# easy-rsa's working directory (PEM files, index, serial).
PKI_DIR = f"{SERVER_DIR}/chaos-pki"
TLS_CRYPT_KEY = f"{SERVER_DIR}/chaos-tls-crypt.key"

# The CA cannot be regenerated, so after every change the whole PKI
# is snapshotted as JSON to /var/lib/chaos-router-os/system/
# openvpn_pki.json and restored from there when PKI_DIR is missing.
# Issued certificates exist the moment they are created, so this is a
# system record, never reverted with the config.
PKI_SNAPSHOT = "openvpn_pki"

# OpenVPN drops to nobody, which must still read the CRL.
PUBLIC_CRL = f"{SERVER_DIR}/chaos-crl.pem"

# Shared up/down hook that adds NAT for VPN traffic.
NAT_SCRIPT = "/etc/openvpn/chaos-nat.sh"

EASYRSA_PATHS = (
    "/usr/share/easy-rsa/easyrsa",
)

CIPHERS = "AES-256-GCM:AES-128-GCM:CHACHA20-POLY1305"

DEFAULT_SERVER = {
    "enabled": False,
    "port": 1194,
    "proto": "udp",
    "network": "10.9.0.0/24",
    "endpoint": "",
    "dns": "1.1.1.1",
    "routing": "full"
}

NAT_SCRIPT_CONTENT = """#!/bin/sh
# Generated by Chaos Router OS. Do not edit by hand.
# OpenVPN up/down hook: NAT for VPN traffic.
#   Server: CHAOS_NAT_SOURCE / CHAOS_WAN set via setenv.
#   Client: masquerade LAN traffic leaving through the tunnel ($dev).

if [ -n "$CHAOS_NAT_SOURCE" ]; then
    RULE="-s $CHAOS_NAT_SOURCE -o $CHAOS_WAN -j MASQUERADE"
else
    RULE="-o $dev -j MASQUERADE"
fi

case "$script_type" in
    up)
        iptables -t nat -C POSTROUTING $RULE 2>/dev/null ||
            iptables -t nat -A POSTROUTING $RULE
        ;;
    down)
        iptables -t nat -D POSTROUTING $RULE 2>/dev/null
        ;;
esac

exit 0
"""


# -------------------------------------------------------------------
# Tools
# -------------------------------------------------------------------

def has_openvpn():

    return which("openvpn") is not None


def get_easyrsa():

    found = which("easyrsa")

    if found:
        return found

    for path in EASYRSA_PATHS:

        if os.path.exists(path):
            return path

    return None


def easyrsa(*args):

    path = get_easyrsa()

    if not path:
        return False, "easy-rsa is not available."

    return run_command(privileged([
        path,
        "--batch",
        f"--pki-dir={PKI_DIR}",
        *args
    ]))


def root_file_exists(path):

    ok, _ = run_command(privileged(["test", "-f", path]))

    return ok


def ensure_nat_script():

    return write_root_file(NAT_SCRIPT, NAT_SCRIPT_CONTENT, mode="755")


# -------------------------------------------------------------------
# PKI
# -------------------------------------------------------------------

def snapshot_pki():
    """
    Saves every file of the PKI (and the tls-crypt key) as JSON.
    """

    ok, output = run_command(privileged([
        "find",
        PKI_DIR,
        "-mindepth",
        "1",
        "-printf",
        "%y %P\\n"
    ]))

    if not ok:
        return False, f"Could not read the PKI: {output}"

    snapshot = {
        "version": 1,
        "dirs": [],
        "files": {},
        "tls_crypt_key": ""
    }

    for line in output.splitlines():

        kind, _, relative = line.partition(" ")

        if kind == "d":
            snapshot["dirs"].append(relative)
            continue

        if kind != "f":
            continue

        ok, content = read_root_file(f"{PKI_DIR}/{relative}")

        # easy-rsa only writes text files; skip anything else.
        if ok:
            snapshot["files"][relative] = content

    if "ca.crt" not in snapshot["files"]:
        return False, "The PKI has no CA certificate."

    ok, key = read_root_file(TLS_CRYPT_KEY)

    if ok:
        snapshot["tls_crypt_key"] = key

    # Holds the CA private key.
    save_system(PKI_SNAPSHOT, snapshot, secret=True)

    return True, "OK"


def restore_pki():
    """
    Recreates PKI_DIR from the JSON snapshot.
    """

    snapshot = load_system(PKI_SNAPSHOT, {})

    if not snapshot.get("files", {}).get("ca.crt"):
        return False

    for directory in [""] + snapshot.get("dirs", []):

        run_command(privileged([
            "install",
            "-d",
            "-m",
            "700",
            f"{PKI_DIR}/{directory}".rstrip("/")
        ]))

    for relative, content in snapshot["files"].items():

        ok, _ = write_root_file(f"{PKI_DIR}/{relative}", content)

        if not ok:
            return False

    if snapshot.get("tls_crypt_key"):
        write_root_file(TLS_CRYPT_KEY, snapshot["tls_crypt_key"])

    return True


def pki_ready():

    if root_file_exists(f"{PKI_DIR}/ca.crt"):
        return True

    return restore_pki() and root_file_exists(f"{PKI_DIR}/ca.crt")


def init_pki():
    """
    Creates the CA, the server certificate, a CRL and the
    tls-crypt key. Safe to call again; existing PKI is kept.
    """

    if pki_ready():
        return True, "OK"

    steps = [
        ("init-pki",),
        # EC keys are small and fast to generate on the Pi.
        ("--use-algo=ec", "--curve=prime256v1",
         "--req-cn=Chaos Router OS CA", "build-ca", "nopass"),
        ("--use-algo=ec", "--curve=prime256v1",
         "build-server-full", "server", "nopass")
    ]

    for step in steps:

        ok, result = easyrsa(*step)

        if not ok:
            return False, f"Certificate setup failed ({step[-2]}): {result}"

    ok, result = run_command(privileged([
        which("openvpn"),
        "--genkey",
        "secret",
        TLS_CRYPT_KEY
    ]))

    if not ok:
        return False, f"Could not create tls-crypt key: {result}"

    return refresh_crl()


def refresh_crl():
    """
    Regenerates the CRL (it expires) and publishes a copy
    readable after OpenVPN drops privileges.
    """

    ok, result = easyrsa("gen-crl")

    if not ok:
        return False, f"Could not generate CRL: {result}"

    ok, crl = read_root_file(f"{PKI_DIR}/crl.pem")

    if not ok:
        return False, crl

    ok, result = write_root_file(PUBLIC_CRL, crl, mode="644")

    if not ok:
        return False, result

    return snapshot_pki()


def read_pem(path):
    """
    Reads a PEM file, dropping easy-rsa's text dump before it.
    """

    ok, content = read_root_file(path)

    if not ok:
        return None

    start = content.find("-----BEGIN")

    return content[start:].strip() if start >= 0 else content.strip()


# -------------------------------------------------------------------
# Settings
# -------------------------------------------------------------------

def load_openvpn():

    data = load_running(OPENVPN_SETTINGS, {})

    server = dict(DEFAULT_SERVER)
    server.update(load_defaults(OPENVPN_SETTINGS).get("server", {}))
    server.update(data.get("server", {}))

    return {
        "server": server,
        "clients": data.get("clients", [])
    }


def save_openvpn(data, confirm=None, apply=True):
    """
    Applies the data through safe apply; returns a result dict.
    """

    return transaction.change(
        OPENVPN_SETTINGS, data, confirm=confirm, apply=apply
    )


def validate_server(server):

    try:
        port = int(server.get("port"))
    except (TypeError, ValueError):
        return False, "Invalid port."

    if not 1 <= port <= 65535:
        return False, "Invalid port."

    proto = server.get("proto")

    if proto not in ("udp", "tcp"):
        return False, "Protocol must be UDP or TCP."

    try:
        network = ipaddress.IPv4Network(str(server.get("network")), strict=True)
    except ValueError:
        return False, "Invalid tunnel network. Use CIDR, e.g. 10.9.0.0/24."

    if not 16 <= network.prefixlen <= 29:
        return False, "Tunnel network must be between /16 and /29."

    for lan in get_lan_networks():

        if network.overlaps(ipaddress.IPv4Network(lan)):
            return False, f"Tunnel network overlaps the LAN ({lan})."

    endpoint = str(server.get("endpoint") or "").strip()

    if endpoint and not all(
        c.isalnum() or c in ".-" for c in endpoint
    ):
        return False, "Invalid public address. Use a hostname or IP."

    dns = [d.strip() for d in str(server.get("dns") or "").split(",") if d.strip()]

    for entry in dns:
        try:
            ipaddress.IPv4Address(entry)
        except ValueError:
            return False, f"Invalid DNS server: {entry}"

    if server.get("routing") not in ("full", "lan"):
        return False, "Invalid routing mode."

    return True, {
        "enabled": server.get("enabled") is True,
        "port": port,
        "proto": proto,
        "network": str(network),
        "endpoint": endpoint,
        "dns": ", ".join(dns),
        "routing": server["routing"]
    }


# -------------------------------------------------------------------
# Config files
# -------------------------------------------------------------------

def render_server_config(server):

    network = ipaddress.IPv4Network(server["network"])

    lines = [
        "# Generated by Chaos Router OS. Do not edit by hand.",
        "# Changes are overwritten from the VPN page.",
        "",
        f"port {server['port']}",
        f"proto {server['proto']}",
        f"dev {SERVER_DEVICE}",
        "dev-type tun",
        "topology subnet",
        f"server {network.network_address} {network.netmask}",
        "",
        f"ca {PKI_DIR}/ca.crt",
        f"cert {PKI_DIR}/issued/server.crt",
        f"key {PKI_DIR}/private/server.key",
        "dh none",
        f"tls-crypt {TLS_CRYPT_KEY}",
        f"crl-verify {PUBLIC_CRL}",
        f"data-ciphers {CIPHERS}",
        "",
        "keepalive 10 120",
        "persist-key",
        "persist-tun",
        "user nobody",
        "group nogroup"
    ]

    if server["proto"] == "udp":
        lines.append("explicit-exit-notify 1")

    lines.append("")

    if server["routing"] == "full":
        lines.append('push "redirect-gateway def1 bypass-dhcp"')
    else:
        for lan in get_lan_networks():
            lan_net = ipaddress.IPv4Network(lan)
            lines.append(
                f'push "route {lan_net.network_address} {lan_net.netmask}"'
            )

    for entry in [d.strip() for d in server["dns"].split(",") if d.strip()]:
        lines.append(f'push "dhcp-option DNS {entry}"')

    lines += [
        "",
        "# NAT so clients reach the internet through the router.",
        "script-security 2",
        f"setenv CHAOS_NAT_SOURCE {network}",
        f"setenv CHAOS_WAN {get_wan_interface()}",
        f"up {NAT_SCRIPT}",
        f"down {NAT_SCRIPT}",
        "",
        "verb 3"
    ]

    return "\n".join(lines) + "\n"


def render_client_config(server, name):

    ca = read_pem(f"{PKI_DIR}/ca.crt")
    cert = read_pem(f"{PKI_DIR}/issued/{name}.crt")
    key = read_pem(f"{PKI_DIR}/private/{name}.key")
    tls = read_pem(TLS_CRYPT_KEY)

    if not all((ca, cert, key, tls)):
        return None

    endpoint = server["endpoint"] or "YOUR_PUBLIC_ADDRESS"

    lines = [
        f"# {name} - generated by Chaos Router OS",
        "client",
        "dev tun",
        f"proto {server['proto']}",
        f"remote {endpoint} {server['port']}",
        "resolv-retry infinite",
        "nobind",
        "persist-key",
        "persist-tun",
        "remote-cert-tls server",
        f"data-ciphers {CIPHERS}",
        "verb 3",
        "",
        "<ca>", ca, "</ca>",
        "<cert>", cert, "</cert>",
        "<key>", key, "</key>",
        "<tls-crypt>", tls, "</tls-crypt>"
    ]

    return "\n".join(lines) + "\n"


def server_firewall_rules(server):

    return firewall_rules_for("OpenVPN", [
        ["allow", "in", "from", "any", "to", "any",
         "port", str(server["port"]), "proto", server["proto"]],
        ["allow", "in", "on", SERVER_DEVICE],
        ["route", "allow", "in", "on", SERVER_DEVICE]
    ])


# -------------------------------------------------------------------
# Apply
# -------------------------------------------------------------------

def apply_server():
    """
    Applies the running OpenVPN server config.
    """

    server = load_openvpn()["server"]

    if not has_openvpn():

        if not server["enabled"]:
            return True, "OpenVPN server stopped."

        return False, "OpenVPN is not available."

    if not server["enabled"]:

        stop_unit(SERVER_UNIT)

        return True, sync_firewall("openvpn", []) or "OpenVPN server stopped."

    for step in (init_pki, refresh_crl, ensure_nat_script):

        ok, result = step()

        if not ok:
            return False, f"OpenVPN could not be prepared: {result}"

    ok, result = write_root_file(
        SERVER_CONF,
        render_server_config(server)
    )

    if not ok:
        return False, f"OpenVPN config could not be written: {result}"

    warning = sync_firewall("openvpn", server_firewall_rules(server))

    ok, result = start_unit(SERVER_UNIT)

    if not ok:
        return False, f"OpenVPN failed to start: {result}"

    return True, warning or "OpenVPN server running."


def verify_server():

    if not load_openvpn()["server"]["enabled"]:
        return True, "OK"

    return unit_stays_active(SERVER_UNIT)


def save_server(settings):
    """
    Validates server settings and applies them through safe apply.
    """

    data = load_openvpn()

    merged = dict(data["server"])
    merged.update(settings or {})

    ok, result = validate_server(merged)

    if not ok:
        return transaction.result(False, result)

    data["server"] = result

    return save_openvpn(data)


# -------------------------------------------------------------------
# Clients
# -------------------------------------------------------------------

def add_client(name):

    data = load_openvpn()

    name = str(name or "").strip()

    if not valid_name(name) or name == "server":
        return False, "Name must be 1-32 letters, numbers, - or _."

    if any(c["name"] == name for c in data["clients"]):
        return False, f"A client named {name} already exists."

    if not has_openvpn():
        return False, "OpenVPN is not available."

    ok, result = init_pki()

    if not ok:
        return False, result

    ok, result = easyrsa(
        "--use-algo=ec",
        "--curve=prime256v1",
        "build-client-full",
        name,
        "nopass"
    )

    if not ok:
        return False, f"Could not create certificate: {result}"

    ok, result = snapshot_pki()

    if not ok:
        return False, f"Certificate created, but not backed up: {result}"

    data["clients"].append({
        "name": name,
        "created": int(time.time())
    })

    # The certificate exists now; record it without restarting the
    # server, which would drop every connected device.
    outcome = save_openvpn(data, apply=False)

    return outcome["success"], (
        "Client added." if outcome["success"] else outcome["message"]
    )


def revoke_client(name):

    data = load_openvpn()

    if not any(c["name"] == name for c in data["clients"]):
        return False, "Client not found."

    ok, result = easyrsa("revoke", name)

    if not ok:
        return False, f"Could not revoke certificate: {result}"

    ok, result = refresh_crl()

    if not ok:
        return False, result

    data["clients"] = [c for c in data["clients"] if c["name"] != name]

    # The CRL is checked on connect; re-applying restarts the server
    # and drops the revoked device's live session.
    outcome = save_openvpn(data, confirm=False)

    return outcome["success"], (
        "Client revoked." if outcome["success"] else outcome["message"]
    )


def get_client_config(name):
    """
    Returns (ok, filename or message, config text).
    """

    data = load_openvpn()

    if not any(c["name"] == name for c in data["clients"]):
        return False, "Client not found.", None

    config = render_client_config(data["server"], name)

    if not config:
        return False, "Could not read the client's certificates.", None

    return True, f"{name}.ovpn", config


# -------------------------------------------------------------------
# Status
# -------------------------------------------------------------------

def get_connected_clients():
    """
    Parses the status file (version 2, comma separated).
    """

    ok, content = read_root_file(STATUS_FILE)

    if not ok:
        return {}

    header = None
    clients = {}

    for row in csv.reader(io.StringIO(content)):

        if not row:
            continue

        if row[0] == "HEADER" and row[1:2] == ["CLIENT_LIST"]:
            header = row[2:]
            continue

        if row[0] != "CLIENT_LIST" or not header:
            continue

        entry = dict(zip(header, row[1:]))

        try:

            clients[entry.get("Common Name", "")] = {
                "real_address": entry.get("Real Address", ""),
                "virtual_address": entry.get("Virtual Address", ""),
                "rx_bytes": int(entry.get("Bytes Received", 0)),
                "tx_bytes": int(entry.get("Bytes Sent", 0)),
                "connected_since": int(entry.get("Connected Since (time_t)", 0))
            }

        except ValueError:
            pass

    return clients


def get_openvpn_status():

    data = load_openvpn()

    installed = has_openvpn()
    running = installed and unit_active(SERVER_UNIT)

    live = get_connected_clients() if running else {}

    clients = []

    for client in data["clients"]:

        info = live.get(client["name"])

        clients.append({
            "name": client["name"],
            "created": client.get("created"),
            "connected": info is not None,
            **(info or {})
        })

    return {
        "installed": installed,
        "easyrsa": get_easyrsa() is not None,
        "running": running,
        "server": data["server"],
        "clients": clients
    }
