import hashlib
import ipaddress
import os
import re
import shutil
import tempfile
import time

from services.config import load_defaults, load_running, save_running

from services import transaction

from services.network import (
    run,
    run_command,
    privileged,
    SETTLE_SECONDS,
    bridges_interface,
    BRIDGE
)

from services.dhcp import get_dhcp_leases

# -------------------------------------------------------------------
# Configuration
# -------------------------------------------------------------------

# wifi.json in /etc/chaos-router-os (defaults) and /var/lib/chaos-router-os.
WIFI_SETTINGS = "wifi"

# One access point per radio: chaos-hostapd@<interface>.service
# (deploy/chaos-hostapd@.service) reads /etc/hostapd/chaos-<interface>.conf.
HOSTAPD_DIR = "/etc/hostapd"
HOSTAPD_UNIT = "chaos-hostapd@{}.service"

# Before there could be several access points, Debian's own
# hostapd.service ran the one access point from this file.
LEGACY_CONF_FILE = "/etc/hostapd/hostapd.conf"
LEGACY_MARKER = "# Generated by Chaos Router OS."

# hostapd lives in /usr/sbin, which is often missing from a user's PATH.
SBIN_PATH = os.pathsep.join([
    os.environ.get("PATH", ""),
    "/usr/sbin",
    "/sbin"
])

BANDS = {
    "2.4": {
        "hw_mode": "g",
        "channels": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13],
        "default": 6
    },
    # Non-DFS channels only; the Pi cannot do radar detection as an AP.
    "5": {
        "hw_mode": "a",
        "channels": [36, 40, 44, 48, 149, 153, 157, 161],
        "default": 36
    },
    # Wi-Fi 6E: 20 MHz channels 1-233. No DFS on 6 GHz.
    "6": {
        "hw_mode": "a",
        "channels": list(range(1, 234, 4)),
        "default": 37
    }
}

# Preferred Scanning Channels: 6 GHz clients find these fastest.
PSC_CHANNELS = list(range(5, 234, 16))

# Frequency ranges (MHz) used to sort `iw phy` channels into bands.
BAND_FREQUENCIES = {
    "2.4": (2400, 2500),
    "5": (5150, 5900),
    "6": (5925, 7125)
}

SECURITY_MODES = (
    "wpa2",
    "wpa2-wpa3",
    "wpa3",
    "open"
)

# wifi.json: the country (one for all radios: it is the router's
# location) and one network per radio:
#
#   {"country": "US", "networks": {"wlan0": {...}, "wlan1": {...}}}
#
# Older versions stored a single network ({"interface": "wlan0",
# "ssid": ...}); it is read as the network of that interface.
DEFAULT_SETTINGS = {
    # Set by the installer; Wi-Fi stays off until there is one.
    "country": "",
    "networks": {}
}

DEFAULT_NETWORK = {
    "enabled": False,
    "ssid": "Chaos Router",
    "password": "",
    "security": "wpa2",
    "band": "2.4",
    "channel": 6,
    "hidden": False,
    "isolate_clients": False,
    # The router's address on this radio, so its Wi-Fi clients get
    # DHCP and reach the router. Not used while the radio is a port of
    # the LAN bridge (it joins br0 instead).
    "address": "10.42.0.1",
    "prefix": 24
}

NETWORK_FIELDS = tuple(DEFAULT_NETWORK)

# /tmp/chaos-router-os/wifi_configs.json: {"wlan0": "<sha256>"}, the
# config each access point runs, so saving one radio does not restart
# (and disconnect) the others.
APPLIED_CONFIGS = "wifi_configs"

# /tmp/chaos-router-os/wifi_address.json: {"wlan0": "10.42.0.1/24"},
# where addresses were set, so they can be removed when an access
# point turns off or joins the bridge.
APPLIED_ADDRESS = "wifi_address"

COUNTRY_RE = re.compile(r"^[A-Z]{2}$")

INTERFACE_RE = re.compile(r"^[A-Za-z0-9_.-]{1,15}$")

# WPA passphrases are 8-63 printable ASCII characters.
PASSPHRASE_RE = re.compile(r"^[\x20-\x7e]{8,63}$")


# -------------------------------------------------------------------
# Helpers
# -------------------------------------------------------------------

def which(name):

    return shutil.which(name, path=SBIN_PATH)


def has_hostapd():

    return which("hostapd") is not None


def is_hostapd_running(interface):

    return run([
        "systemctl",
        "is-active",
        unit_name(interface)
    ]) == "active"


def get_wireless_interfaces():

    interfaces = []

    try:
        names = sorted(os.listdir("/sys/class/net"))
    except Exception:
        return interfaces

    for name in names:

        if os.path.exists(f"/sys/class/net/{name}/wireless"):
            interfaces.append(name)

    return interfaces


def get_band_support(interface):
    """
    Channels the interface's radio supports per band, from
    `iw phy <phy> info`. Returns None when it cannot be detected
    (no iw, no such interface), so callers fall back to BANDS.
    """

    iw = which("iw")

    try:
        with open(f"/sys/class/net/{interface}/phy80211/name") as f:
            phy = f.read().strip()
    except Exception:
        return None

    if not iw or not phy:
        return None

    output = run([iw, "phy", phy, "info"])

    if not output:
        return None

    support = {band: [] for band in BANDS}

    # e.g. "* 5955.0 MHz [1] (23.0 dBm)" or "* 6435 MHz [97] (disabled)"
    pattern = re.compile(r"\*\s+(\d+)(?:\.\d+)?\s+MHz\s+\[(\d+)\](.*)")

    for line in output.splitlines():

        match = pattern.search(line)

        if not match:
            continue

        freq = int(match.group(1))
        channel = int(match.group(2))

        # "no IR" can lift once hostapd sets the country, so only
        # channels the hardware disables outright are skipped.
        if "disabled" in match.group(3):
            continue

        for band, (low, high) in BAND_FREQUENCIES.items():

            if low <= freq <= high and channel in BANDS[band]["channels"]:
                support[band].append(channel)

    return support


# -------------------------------------------------------------------
# Settings
# -------------------------------------------------------------------

def normalize(data):
    """
    {"country", "networks"} from stored settings, in the current or
    the old single-network format.
    """

    data = data if isinstance(data, dict) else {}

    networks = data.get("networks")

    if isinstance(networks, dict):
        networks = {
            name: {**DEFAULT_NETWORK, **{k: v for k, v in net.items() if k in NETWORK_FIELDS}}
            for name, net in networks.items()
            if isinstance(net, dict) and INTERFACE_RE.fullmatch(str(name))
        }
    elif data.get("interface"):
        # Old format: one network, flat.
        networks = {
            str(data["interface"]): {
                **DEFAULT_NETWORK,
                **{k: data[k] for k in NETWORK_FIELDS if k in data}
            }
        }
    else:
        networks = {}

    return {
        "country": str(data.get("country") or "").upper(),
        "networks": networks
    }


def get_wifi_settings():

    # Each layer on its own: the two formats cannot be merged key by key.
    defaults = normalize(load_defaults(WIFI_SETTINGS, DEFAULT_SETTINGS))

    running = load_running(WIFI_SETTINGS, None)

    if not isinstance(running, dict):
        return defaults

    settings = normalize(running)

    settings["country"] = settings["country"] or defaults["country"]

    return settings


def off_settings():
    """
    Every access point off (factory reset, uninstall); the country stays.
    """

    return {"country": get_wifi_settings()["country"], "networks": {}}


def suggest_address(interface, settings):
    """
    A free subnet for a radio without settings: 10.42.0.1/24 for the
    first, then 10.43.0.1/24, ...
    """

    used = set()

    for name, net in settings["networks"].items():

        if name == interface:
            continue

        try:
            used.add(ipaddress.IPv4Interface(f"{net['address']}/{net['prefix']}").network)
        except ValueError:
            pass

    for second in range(42, 255):

        network = ipaddress.IPv4Network(f"10.{second}.0.0/24")

        if not any(network.overlaps(u) for u in used):
            return f"10.{second}.0.1", 24

    return DEFAULT_NETWORK["address"], DEFAULT_NETWORK["prefix"]


def get_network(interface, settings=None):
    """
    One radio's network, flat as the WiFi page edits it:
    {"interface", "country", "enabled", "ssid", ...}. A radio without
    settings gets the defaults with a free subnet.
    """

    settings = settings or get_wifi_settings()

    net = settings["networks"].get(interface)

    if net is None:
        address, prefix = suggest_address(interface, settings)
        net = {**DEFAULT_NETWORK, "address": address, "prefix": prefix}

    return {**net, "interface": interface, "country": settings["country"]}


def get_networks(settings=None):
    """
    {interface: network} for every radio there is, and every radio
    with settings (e.g. an unplugged USB adapter).
    """

    settings = settings or get_wifi_settings()

    names = sorted(set(get_wireless_interfaces()) | set(settings["networks"]))

    return {name: get_network(name, settings) for name in names}


def enabled_networks(settings=None):
    """
    The networks that are on, as flat settings.
    """

    settings = settings or get_wifi_settings()

    return [
        get_network(name, settings)
        for name, net in sorted(settings["networks"].items())
        if net["enabled"]
    ]


def validate_network(data, settings=None):
    """
    Validates and normalises one radio's network (flat, with
    "interface" and "country").

    Returns (True, network) or (False, message).
    """

    data = data or {}
    settings = settings or get_wifi_settings()

    interface = str(data.get("interface") or "").strip()

    if not INTERFACE_RE.fullmatch(interface):
        return False, "Invalid interface."

    net = get_network(interface, settings)
    net.update(data)

    enabled = net.get("enabled") is True

    if enabled and interface not in get_wireless_interfaces():
        return False, f"{interface} is not a wireless interface."

    ssid = str(net.get("ssid") or "")

    if not ssid.strip():
        return False, "Network name cannot be empty."

    if len(ssid.encode("utf-8")) > 32:
        return False, "Network name is too long (max 32 bytes)."

    if any(ord(c) < 0x20 or ord(c) == 0x7f for c in ssid):
        return False, "Network name contains invalid characters."

    security = net.get("security")

    if security not in SECURITY_MODES:
        return False, "Invalid security mode."

    password = str(net.get("password") or "")

    if security != "open" and not PASSPHRASE_RE.fullmatch(password):
        return False, (
            "Password must be 8-63 characters "
            "(letters, numbers, symbols and spaces)."
        )

    band = str(net.get("band"))

    if band not in BANDS:
        return False, "Invalid band."

    try:
        channel = int(net.get("channel"))
    except (TypeError, ValueError):
        return False, "Invalid channel."

    if channel not in BANDS[band]["channels"]:
        return False, f"Channel {channel} is not available on {band} GHz."

    # 6 GHz only allows WPA3-SAE (open networks would need OWE).
    if band == "6" and security != "wpa3":
        return False, "6 GHz requires WPA3 Personal."

    if enabled:

        support = get_band_support(interface)

        if support is not None:

            if not support[band]:
                return False, f"{interface} does not support {band} GHz."

            if channel not in support[band]:
                return False, (
                    f"{interface} does not support channel "
                    f"{channel} on {band} GHz."
                )

    country = str(net.get("country") or "").strip().upper()

    if country and not COUNTRY_RE.fullmatch(country):
        return False, "Country must be a two-letter code, e.g. US or DE."

    if enabled and not country:
        return False, "Set the country first: it decides which channels are allowed."

    bridged = bridges_interface(interface)

    ok, result = validate_address(
        net.get("address"), net.get("prefix"), interface,
        check_overlap=enabled and not bridged,
        settings=settings
    )

    if not ok:
        return False, result

    address, prefix = result

    return True, {
        "interface": interface,
        "country": country,
        "enabled": enabled,
        "ssid": ssid,
        "password": password if security != "open" else "",
        "security": security,
        "band": band,
        "channel": channel,
        "hidden": net.get("hidden") is True,
        "isolate_clients": net.get("isolate_clients") is True,
        "address": address,
        "prefix": prefix
    }


def with_network(settings, network):
    """
    The whole Wi-Fi settings with one radio's network replaced.
    """

    return {
        "country": network["country"] or settings["country"],
        "networks": {
            **settings["networks"],
            network["interface"]: {k: network[k] for k in NETWORK_FIELDS}
        }
    }


def validate_wifi_settings(data):
    """
    Validates the whole Wi-Fi settings (e.g. from a backup), in the
    current or the old format. Returns (True, settings) or (False, message).
    """

    data = normalize(data)

    result = {"country": data["country"], "networks": {}}

    for name, net in sorted(data["networks"].items()):

        # Radios that are not here now (USB adapter) are kept as they
        # are, switched off.
        if name not in get_wireless_interfaces():
            result["networks"][name] = {**net, "enabled": False}
            continue

        ok, checked = validate_network(
            {**net, "interface": name, "country": data["country"]},
            settings=result
        )

        if not ok:
            return False, f"{name}: {checked}"

        result = with_network(result, checked)

    return True, result


def get_other_networks(interface, settings=None):
    """
    [(name, IPv4Network)] the access point's subnet must not overlap:
    every IPv4 address on other interfaces, and the subnets of the
    other radios' networks that are on.
    """

    networks = []

    applied = applied_addresses()

    for line in (run(["ip", "-4", "-o", "addr", "show"]) or "").splitlines():

        parts = line.split()

        if len(parts) < 4 or parts[2] != "inet":
            continue

        name = parts[1]

        # Its own address is replaced anyway.
        if name in ("lo", interface):
            continue

        try:
            networks.append((name, ipaddress.IPv4Interface(parts[3]).network))
        except ValueError:
            pass

    settings = settings or get_wifi_settings()

    for name, net in settings["networks"].items():

        if name == interface or not net["enabled"] or name in applied:
            continue

        if bridges_interface(name):
            continue

        try:
            networks.append((name, ipaddress.IPv4Interface(f"{net['address']}/{net['prefix']}").network))
        except ValueError:
            pass

    return networks


def validate_address(address, prefix, interface, check_overlap=True, settings=None):
    """
    Returns (True, (address, prefix)) or (False, message).
    """

    try:
        ip = ipaddress.IPv4Address(str(address or "").strip())
    except ValueError:
        return False, "Invalid router address."

    try:
        prefix = int(prefix)
    except (TypeError, ValueError):
        return False, "Invalid prefix (CIDR), e.g. 24."

    if not 8 <= prefix <= 30:
        return False, "The prefix (CIDR) must be between 8 and 30."

    network = ipaddress.IPv4Interface(f"{ip}/{prefix}").network

    if ip in (network.network_address, network.broadcast_address):
        return False, f"{ip} is the network or broadcast address of {network}."

    if check_overlap:

        for name, other in get_other_networks(interface, settings):

            if network.overlaps(other):
                return False, (
                    f"{network} overlaps {other} on {name}. "
                    f"Choose another subnet, e.g. {suggest_address(interface, settings or get_wifi_settings())[0]}/24."
                )

    return True, (str(ip), prefix)


# -------------------------------------------------------------------
# hostapd config
# -------------------------------------------------------------------

def config_path(interface):

    return os.path.join(HOSTAPD_DIR, f"chaos-{interface}.conf")


def unit_name(interface):

    return HOSTAPD_UNIT.format(interface)


def config_files():
    """
    Every hostapd config Chaos Router OS wrote (for factory reset and
    uninstall).
    """

    try:
        names = os.listdir(HOSTAPD_DIR)
    except OSError:
        names = []

    files = [
        os.path.join(HOSTAPD_DIR, n) for n in sorted(names)
        if n.startswith("chaos-") and n.endswith(".conf")
    ]

    if is_legacy_config():
        files.append(LEGACY_CONF_FILE)

    return files


def render_hostapd_config(settings):

    band = BANDS[settings["band"]]

    lines = [
        "# Generated by Chaos Router OS. Do not edit by hand.",
        "# Changes are overwritten from the WiFi page.",
        f"# Access point on {settings['interface']} (chaos-hostapd@{settings['interface']}).",
        "",
        f"interface={settings['interface']}",
        # One LAN: the access point joins the LAN bridge.
        *([f"bridge={BRIDGE}"] if bridges_interface(settings["interface"]) else []),
        "driver=nl80211",
        "ctrl_interface=/var/run/hostapd",
        "ctrl_interface_group=0",
        "",
        # Hex form needs no escaping for any SSID characters.
        f"ssid2={settings['ssid'].encode('utf-8').hex()}",
        "utf8_ssid=1",
        f"ignore_broadcast_ssid={1 if settings['hidden'] else 0}",
        "",
        f"country_code={settings['country']}",
        "ieee80211d=1",
        f"hw_mode={band['hw_mode']}",
        f"channel={settings['channel']}",
        "wmm_enabled=1"
    ]

    if settings["band"] == "6":

        # 6 GHz is HE (802.11ax) only; HT/VHT are not used there.
        # Operating class 131 is 20 MHz.
        lines += [
            "op_class=131",
            "ieee80211ax=1"
        ]

    else:

        lines.append("ieee80211n=1")

        if settings["band"] == "5":
            lines.append("ieee80211ac=1")

    lines.append(f"ap_isolate={1 if settings['isolate_clients'] else 0}")

    security = settings["security"]

    if security != "open":

        key_mgmt = {
            "wpa2": "WPA-PSK",
            "wpa2-wpa3": "WPA-PSK SAE",
            "wpa3": "SAE"
        }[security]

        lines += [
            "",
            "auth_algs=1",
            "wpa=2",
            f"wpa_key_mgmt={key_mgmt}",
            "rsn_pairwise=CCMP",
            f"wpa_passphrase={settings['password']}"
        ]

        # WPA3 requires protected management frames.
        if security == "wpa3":
            lines.append("ieee80211w=2")
        elif security == "wpa2-wpa3":
            lines.append("ieee80211w=1")

        if security != "wpa2":
            lines.append(f"sae_password={settings['password']}")

        # 6 GHz only allows hash-to-element SAE.
        if settings["band"] == "6":
            lines.append("sae_pwe=1")

    return "\n".join(lines) + "\n"


def install_hostapd_config(content, path):

    fd, tmp = tempfile.mkstemp(
        prefix="chaos-hostapd-",
        suffix=".conf"
    )

    try:

        with os.fdopen(fd, "w") as f:
            f.write(content)

        ok, result = run_command(privileged([
            "mkdir",
            "-p",
            HOSTAPD_DIR
        ]))

        if not ok:
            return False, result

        # 600: the file contains the Wi-Fi password.
        return run_command(privileged([
            "install",
            "-m",
            "600",
            tmp,
            path
        ]))

    finally:

        os.unlink(tmp)


def set_networkmanager_managed(interface, managed):
    """
    NetworkManager must leave the interface alone while hostapd
    runs the access point.
    """

    if not which("nmcli"):
        return True, "OK"

    return run_command(privileged([
        "nmcli",
        "device",
        "set",
        interface,
        "managed",
        "yes" if managed else "no"
    ]))


def get_hostapd_error(interface):

    ok, output = run_command(privileged([
        "journalctl",
        "-u",
        unit_name(interface),
        "-n",
        "5",
        "--no-pager",
        "-o",
        "cat"
    ]))

    return output if ok and output else "hostapd failed to start."


# -------------------------------------------------------------------
# Apply
# -------------------------------------------------------------------

def save_wifi_settings(data):
    """
    Validates one radio's network, then applies all of them through
    safe apply. Returns a transaction result dict with the networks.
    """

    settings = get_wifi_settings()

    ok, result = validate_network(data, settings)

    if not ok:
        return transaction.result(False, result)

    outcome = transaction.change(WIFI_SETTINGS, with_network(settings, result))

    if outcome["success"] and result["enabled"] and not bridges_interface(result["interface"]):

        # DHCP follows the access point: its radio is served in the
        # new subnet (and confirmed or reverted together with it).
        from services import dhcp

        follow = dhcp.follow_wifi(result["interface"], result["address"], result["prefix"])

        if follow and not follow["success"]:
            outcome["message"] += f" DHCP on {result['interface']}: {follow['message']}"
        elif follow:
            outcome["message"] += f" DHCP now serves {result['interface']}."
            outcome["pending"] = follow.get("pending") or outcome.get("pending")

    outcome["networks"] = get_networks()

    return outcome


def running_instances():
    """
    Interfaces with an access point unit loaded, e.g. ["wlan0"].
    """

    output = run([
        "systemctl", "list-units", "--all", "--plain", "--no-legend",
        "chaos-hostapd@*"
    ]) or ""

    names = []

    for line in output.splitlines():

        unit = line.split()[0] if line.split() else ""

        if unit.startswith("chaos-hostapd@") and unit.endswith(".service"):
            names.append(unit[len("chaos-hostapd@"):-len(".service")])

    return names


def is_legacy_config():

    try:
        with open(LEGACY_CONF_FILE) as f:
            return f.readline().startswith(LEGACY_MARKER)
    except OSError:
        return False


def stop_legacy():
    """
    Moves off Debian's hostapd.service, which ran the one access point
    of older versions: it would fight over the radio.
    """

    if not is_legacy_config():
        return

    for cmd in (
        ["systemctl", "stop", "hostapd"],
        ["systemctl", "disable", "hostapd"],
        ["rm", "-f", LEGACY_CONF_FILE]
    ):
        run_command(privileged(cmd))


def apply_wifi_settings():
    """
    Applies the running Wi-Fi settings: an access point on every radio
    whose network is on, none on the others.
    """

    settings = get_wifi_settings()

    wanted = enabled_networks(settings)

    if not has_hostapd():

        if not wanted:
            return True, "Access points turned off."

        return False, "hostapd is not available."

    stop_legacy()

    present = set(get_wireless_interfaces())
    on = {net["interface"] for net in wanted if net["interface"] in present}

    # Off first: a radio's subnet may move to another one.
    for name in sorted(set(running_instances()) | set(applied_addresses()) | set(settings["networks"])):

        if name in on:
            continue

        ok, result = stop_access_point(name)

        if not ok:
            return False, result

    messages = []

    for net in wanted:

        # An unplugged USB adapter: its network starts when it is back
        # and the settings are applied again.
        if net["interface"] not in present:
            messages.append(f"{net['interface']} is not plugged in.")
            continue

        ok, result = start_access_point(net)

        if not ok:
            return False, f"{net['interface']}: {result}"

        if not result.endswith("unchanged."):
            messages.append(result)

    if messages:
        return True, " ".join(messages)

    return True, "Access points unchanged." if on else "Access points turned off."


def stop_access_point(interface):

    unit = unit_name(interface)

    if interface in running_instances():

        for cmd in (
            ["systemctl", "stop", unit],
            ["systemctl", "disable", unit]
        ):
            ok, result = run_command(privileged(cmd))

            if not ok:
                return False, f"The access point on {interface} could not be stopped: {result}"

    clear_address(interface)

    applied = load_running(APPLIED_CONFIGS, None) or {}

    if applied.pop(interface, None):
        save_running(APPLIED_CONFIGS, applied)

    if os.path.exists(config_path(interface)):
        run_command(privileged(["rm", "-f", config_path(interface)]))

    if interface in get_wireless_interfaces():
        set_networkmanager_managed(interface, True)

    return True, f"Access point on {interface} turned off."


def start_access_point(settings):
    """
    Starts the access point of one radio (flat settings with
    "interface" and "country") and gives the radio its address, or
    joins it to the LAN bridge. Also used for the setup Wi-Fi.
    """

    interface = settings["interface"]

    config = render_hostapd_config(settings)
    digest = hashlib.sha256(config.encode("utf-8")).hexdigest()

    applied = load_running(APPLIED_CONFIGS, None) or {}

    # Unchanged and running: its devices stay connected.
    if applied.get(interface) == digest and is_hostapd_running(interface) and (
        bridges_interface(interface)
        or has_address(interface, settings["address"], settings["prefix"])
    ):
        return True, f"Access point on {interface} unchanged."

    ok, result = install_hostapd_config(config, config_path(interface))

    if not ok:
        return False, f"Wi-Fi settings could not be applied: {result}"

    ok, result = set_networkmanager_managed(interface, False)

    if not ok:
        return False, (
            f"NetworkManager could not release {interface}: {result}"
        )

    commands = []

    # Raspberry Pi OS soft-blocks Wi-Fi until a country is set.
    if which("rfkill"):
        commands.append(["rfkill", "unblock", "wlan"])

    unit = unit_name(interface)

    commands += [
        ["systemctl", "enable", unit],
        ["systemctl", "restart", unit]
    ]

    for cmd in commands:

        ok, result = run_command(privileged(cmd))

        if not ok:

            if cmd[1] == "restart":
                result = get_hostapd_error(interface)

            return False, f"Wi-Fi settings could not be applied: {result}"

    applied[interface] = digest
    save_running(APPLIED_CONFIGS, applied)

    # Bridged: the access point is a port of br0 and has no address.
    if bridges_interface(interface):

        clear_address(interface)

        return True, f"Access point on {interface} applied (LAN bridge)."

    ok, result = set_address(interface, settings["address"], settings["prefix"])

    if not ok:
        return False, f"The address could not be set on {interface}: {result}"

    return True, f"Access point on {interface} applied, {settings['address']}/{settings['prefix']}."


def verify_wifi_settings():

    wanted = [
        net for net in enabled_networks()
        if net["interface"] in get_wireless_interfaces()
    ]

    if not wanted:
        return True, "OK"

    # hostapd gives up shortly after a "successful" start.
    time.sleep(SETTLE_SECONDS)

    for net in wanted:

        interface = net["interface"]

        if not is_hostapd_running(interface):
            return False, f"The access point on {interface} stopped right after starting. {get_hostapd_error(interface)}"

        if not bridges_interface(interface) and not has_address(interface, net["address"], net["prefix"]):
            return False, f"{net['address']}/{net['prefix']} is not set on {interface}."

    return True, "OK"


def ip_command(*args):

    return run_command(privileged(["ip", *args]))


def applied_addresses():
    """
    {interface: "address/prefix"} set by the access points.
    """

    applied = load_running(APPLIED_ADDRESS, None) or {}

    # Older format: one access point.
    if "interface" in applied:
        return {applied["interface"]: applied.get("address")} if applied["interface"] else {}

    return {k: v for k, v in applied.items() if isinstance(v, str)}


def clear_address(interface):
    """
    Removes the address an access point set on this interface.
    """

    applied = applied_addresses()

    if interface in applied:
        ip_command("-4", "addr", "flush", "dev", interface)
        del applied[interface]
        save_running(APPLIED_ADDRESS, applied)


def set_address(interface, address, prefix):
    """
    The equivalent of `ip addr add 10.42.0.1/24 dev wlan1`, replacing
    whatever IPv4 address the interface had.
    """

    ok, result = ip_command("-4", "addr", "flush", "dev", interface)

    if not ok:
        return False, result

    ok, result = ip_command("addr", "add", f"{address}/{prefix}", "dev", interface)

    if not ok:
        return False, result

    applied = applied_addresses()
    applied[interface] = f"{address}/{prefix}"
    save_running(APPLIED_ADDRESS, applied)

    return True, "OK"


def has_address(interface, address, prefix):

    output = run(["ip", "-4", "-o", "addr", "show", "dev", interface]) or ""

    return f"inet {address}/{prefix} " in output + " "


# -------------------------------------------------------------------
# Clients
# -------------------------------------------------------------------

def get_wifi_clients(interface=None):
    """
    Clients of every access point (or of one), each with its
    "interface".
    """

    names = [interface] if interface else [n["interface"] for n in enabled_networks()]

    clients = []

    for name in names:
        clients += get_station_clients(name)

    return clients


def get_station_clients(interface):
    """
    Parses `iw dev <iface> station dump` and matches hostnames
    from the DHCP leases.
    """

    iw = which("iw")

    if not iw or interface not in get_wireless_interfaces():
        return []

    ok, output = run_command(privileged([
        iw,
        "dev",
        interface,
        "station",
        "dump"
    ]))

    if not ok or not output:
        return []

    leases = {
        lease["mac"]: lease
        for lease in get_dhcp_leases()
    }

    clients = []
    current = None

    for line in output.splitlines():

        if line.startswith("Station "):

            mac = line.split()[1].upper()
            lease = leases.get(mac, {})

            current = {
                "interface": interface,
                "mac": mac,
                "hostname": lease.get("hostname", ""),
                "ip": lease.get("ip", ""),
                "signal": None,
                "connected": None,
                "rx_bytes": 0,
                "tx_bytes": 0
            }

            clients.append(current)
            continue

        if not current or ":" not in line:
            continue

        key, value = line.strip().split(":", 1)
        value = value.strip()

        try:

            if key == "signal":
                current["signal"] = int(value.split()[0])
            elif key == "connected time":
                current["connected"] = int(value.split()[0])
            elif key == "rx bytes":
                current["rx_bytes"] = int(value)
            elif key == "tx bytes":
                current["tx_bytes"] = int(value)

        except (ValueError, IndexError):
            pass

    return clients


# -------------------------------------------------------------------
# Status
# -------------------------------------------------------------------

def get_wifi_status():

    installed = has_hostapd()

    running = {
        name: installed and is_hostapd_running(name)
        for name in get_networks()
    }

    return {
        "installed": installed,
        "running": running,
        "config_dir": HOSTAPD_DIR
    }


def get_wifi_options():

    return {
        "bands": {
            band: {
                "channels": info["channels"],
                "default": info["default"]
            }
            for band, info in BANDS.items()
        },
        "psc_channels": PSC_CHANNELS,
        "security": list(SECURITY_MODES),
        # Per interface: channels per band, or null when unknown.
        "support": {
            interface: get_band_support(interface)
            for interface in get_wireless_interfaces()
        }
    }
